enum ActionID
{
    ACTION_NONE,
    ACTION_ATTACK,
    DEPOSIT_ACTION,
    WITHDRAW_ACTION,
    GATHER_ACTION,
    IDLE_ACTION,
    MOVE_ACTION,
    SMELT_ACTION,
    PICK_UP_ACTION,
    SACRIFICE_ACTION
};