enum class EntityID
{
    NONE,
    RESOURCE_TREE,
    RESOURCE_ROCK,
    STRUCTURE_STOCKPILE,
    STRUCTURE_OBELISK,
    STRUCTURE_ALTAR,
    MONSTER_ORC,
    MONSTER_SPIDER_QUEEN,
    EFFECT_BEAM,
    PEON,
    PEON_WIZARD,
    PEON_WARRIOR,
    ITEM_DROP
};